version: "3"

services:
  postgres:
    image: postgres:11.4-alpine
    restart: always
    environment:
      TZ: "Asia/Tokyo"
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: noteria
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - 8080:80
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin:/var/lib/pgadmin
    depends_on:
      - postgres

volumes:
  postgres:
  pgadmin:
